name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify --batch-mode

      - name: Run Tests
        run: mvn test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.java.binaries=target
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #   SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        #   SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: leave_mgt
          path: target/*.jar
