name: Release Workflow
on:
  push:
    tags:
      - 'v*.*.*'  # Matches semantic versioning tags like v1.0.0
jobs:
## for uploading the image to dockerhub
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install --batch-mode
     
      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/leave_management:${{ github.ref_name }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/leave_management:${{ github.ref_name }}
